packaging_format = 2

id = "chatgpt-web"
name = "chatGPT-web"
description.en = "ChatGPT web interface using the OpenAI API"
description.fr = "Interface Web ChatGPT utilisant l'API OpenAI"

version = "2026.04.27~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
website = "https://niek.github.io/chatgpt-web/"
demo = "https://niek.github.io/chatgpt-web/"
code = "https://github.com/Niek/chatgpt-web"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/Niek/chatgpt-web/archive/7dc75d2a699f48695d2d3b5d9e92d298106b7684.tar.gz"
        sha256 = "35eab3dd90e0df4248aa8a48239ce74122b1fcc5c939a623e2c54be6840f59a7"
        autoupdate.upstream = "https://github.com/Niek/chatgpt-web"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5174

    [resources.nodejs]
    version = "22"
