packaging_format = 2

id = "chatgpt-web"
name = "chatGPT-web"
description.en = "ChatGPT web interface using the OpenAI API"
description.fr = "Interface Web ChatGPT utilisant l'API OpenAI"

version = "2026.09.07~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
website = "https://niek.github.io/chatgpt-web/"
demo = "https://niek.github.io/chatgpt-web/"
code = "https://github.com/Niek/chatgpt-web"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/Niek/chatgpt-web/archive/61e98cedbc1cdd4a288b34123ead2cd290ee55cd.tar.gz"
        sha256 = "f558dd54e1d09986598ff6eab5ee82b8138085cdff6bf66aa1081971a7d5af7c"
        autoupdate.upstream = "https://github.com/Niek/chatgpt-web"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5174

    [resources.nodejs]
    version = "22"
